# Generated by Django 4.1.7 on 2023-04-03 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alerta',
            fields=[
                ('idalerta', models.AutoField(db_column='IDAlerta', primary_key=True, serialize=False)),
                ('hora', models.DateTimeField(db_column='Hora')),
                ('sala', models.IntegerField(blank=True, db_column='Sala', null=True)),
                ('sensor', models.IntegerField(blank=True, db_column='Sensor', null=True)),
                ('leitura', models.DecimalField(blank=True, db_column='Leitura', decimal_places=2, max_digits=4, null=True)),
                ('tipoalerta', models.CharField(db_column='TipoAlerta', max_length=20)),
                ('mensagem', models.CharField(db_column='Mensagem', max_length=100)),
                ('horaescrita', models.DateTimeField(db_column='HoraEscrita')),
                ('idexperiencia', models.IntegerField(blank=True, db_column='IDExperiencia', null=True)),
            ],
            options={
                'db_table': 'alerta',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.IntegerField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.IntegerField()),
                ('is_active', models.IntegerField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.PositiveSmallIntegerField()),
                ('change_message', models.TextField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Experiencia',
            fields=[
                ('idexperiencia', models.AutoField(db_column='IDExperiencia', primary_key=True, serialize=False)),
                ('descricao', models.TextField(db_column='Descricao')),
                ('investigador', models.CharField(db_column='Investigador', max_length=50)),
                ('datahora', models.DateTimeField(db_column='DataHora')),
                ('numeroratos', models.IntegerField(db_column='NumeroRatos')),
                ('limiteratossala', models.IntegerField(db_column='LimiteRatosSala')),
                ('segundossemmovimento', models.IntegerField(db_column='SegundosSemMovimento')),
                ('temperaturaideal', models.DecimalField(db_column='TemperaturaIdeal', decimal_places=2, max_digits=4)),
                ('variacaotemperaturamaxima', models.DecimalField(db_column='VariacaoTemperaturaMaxima', decimal_places=2, max_digits=4)),
            ],
            options={
                'db_table': 'experiencia',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Medicoespassagens',
            fields=[
                ('idmedicao', models.AutoField(db_column='IDMedicao', primary_key=True, serialize=False)),
                ('hora', models.DateTimeField(db_column='Hora')),
                ('salaentrada', models.IntegerField(db_column='SalaEntrada')),
                ('salasaida', models.IntegerField(db_column='SalaSaida')),
                ('idmongo', models.IntegerField(db_column='IDMongo')),
                ('idexperiencia', models.IntegerField(blank=True, db_column='IDExperiencia', null=True)),
            ],
            options={
                'db_table': 'medicoespassagens',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Medicoessalas',
            fields=[
                ('idexperiencia', models.IntegerField(db_column='IDExperiencia', primary_key=True, serialize=False)),
                ('numeroratosfinal', models.IntegerField(db_column='NumeroRatosFinal')),
                ('sala', models.IntegerField(db_column='Sala')),
                ('hora', models.DateTimeField(db_column='Hora')),
            ],
            options={
                'db_table': 'medicoessalas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Medicoestemperatura',
            fields=[
                ('idmedicao', models.AutoField(db_column='IDMedicao', primary_key=True, serialize=False)),
                ('hora', models.DateTimeField(db_column='Hora')),
                ('leitura', models.DecimalField(db_column='Leitura', decimal_places=2, max_digits=4)),
                ('sensor', models.IntegerField(db_column='Sensor')),
                ('idmongo', models.IntegerField(db_column='IDMongo')),
                ('idexperiencia', models.IntegerField(blank=True, db_column='IDExperiencia', null=True)),
            ],
            options={
                'db_table': 'medicoestemperatura',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Odoresexperiencia',
            fields=[
                ('sala', models.IntegerField(db_column='Sala', primary_key=True, serialize=False)),
                ('codigoodor', models.CharField(db_column='CodigoOdor', max_length=5)),
            ],
            options={
                'db_table': 'odoresexperiencia',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Parametrosadicionais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datahorainicio', models.DateTimeField(blank=True, db_column='DataHoraInicio', null=True)),
                ('datahorafim', models.DateTimeField(blank=True, db_column='DataHoraFim', null=True)),
                ('razaofim', models.TextField(blank=True, db_column='RazaoFim', null=True)),
                ('variosatributosalertasaadicionar', models.IntegerField(db_column='VariosAtributosAlertasAAdicionar')),
            ],
            options={
                'db_table': 'parametrosadicionais',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Substanciasexperiencia',
            fields=[
                ('numeroratos', models.IntegerField(db_column='NumeroRatos')),
                ('codigosubstancia', models.CharField(db_column='CodigoSubstancia', max_length=5, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'substanciasexperiencia',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Utilizador',
            fields=[
                ('nomeutilizador', models.CharField(db_column='NomeUtilizador', max_length=100)),
                ('telefoneutilizador', models.CharField(db_column='TelefoneUtilizador', max_length=12)),
                ('tipoutilizador', models.CharField(db_column='TipoUtilizador', max_length=3)),
                ('emailutilizador', models.CharField(db_column='EmailUtilizador', max_length=50, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'utilizador',
                'managed': False,
            },
        ),
    ]
